const TopRatedTypes = {
  FETCH_TOPRATED_START: 'FETCH_TOPRATED_START',
  FETCH_TOPRATED_SUCCESS: 'FETCH_TOPRATED_SUCCESS',
  FETCH_TOPRATED_FAILURE: 'FETCH_TOPRATED_FAILURE',
};

export default TopRatedTypes;
