const WatchlistActionTypes = {
  FETCH_WATCHLIST_START: 'FETCH_WATCHLIST_START',
  FETCH_WATCHLIST_SUCCESS: 'FETCH_WATCHLIST_SUCCESS',
  FETCH_WATCHLIST_FAILURE: 'FETCH_WATCHLIST_FAILURE',
};

export default WatchlistActionTypes;
