const SimilarActionTypes = {
  FETCH_SIMILAR_START: 'FETCH_SIMILAR_START',
  FETCH_SIMILAR_SUCCESS: 'FETCH_SIMILAR_SUCCESS',
  FETCH_SIMILAR_FAILURE: 'FETCH_SIMILAR_FAILURE',
};

export default SimilarActionTypes;
