const UserActionTypes = {
  FETCH_TOKEN_START: 'FETCH_TOKEN_START',
  FETCH_TOKEN_SUCCESS: 'FETCH_TOKEN_SUCCESS',
  FETCH_TOKEN_FAILURE: 'FETCH_TOKEN_FAILURE',

  FETCH_SESSION_START: 'FETCH_SESSION_START',
  FETCH_SESSION_SUCCESS: 'FETCH_SESSION_SUCCESS',
  FETCH_SESSION_FAILURE: 'FETCH_SESSION_FAILURE',

  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
};

export default UserActionTypes;
