const FavoritesActionTypes = {
  FETCH_FAVORITES_START: 'FETCH_FAVORITES_START',
  FETCH_FAVORITES_SUCCESS: 'FETCH_FAVORITES_SUCCESS',
  FETCH_FAVORITES_FAILURE: 'FETCH_FAVORITES_FAILURE',
};

export default FavoritesActionTypes;
