export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST'
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES'
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES'
export const GET_SIMILAR_MOVIES = 'GET_SIMILAR_MOVIES'

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL'
export const GET_MOVIE_TRAILER = 'GET_MOVIE_TRAILER'
export const GET_MOVIE_REVIEW = 'GET_MOVIE_REVIEWS'
