const TrailerActionTypes = {
  FETCH_TRAILER_START: 'FETCH_TRAILER_START',
  FETCH_TRAILER_SUCCESS: 'FETCH_TRAILER_SUCCESS',
  FETCH_TRAILER_FAILURE: 'FETCH_TRAILER_FAILURE',
};

export default TrailerActionTypes;
