const NowPlayingActionTypes = {
  FETCH_NOWPLAYING_START: 'FETCH_NOWPLAYING_START',
  FETCH_NOWPLAYING_SUCCESS: 'FETCH_NOWPLAYING_SUCCESS',
  FETCH_NOWPLAYING_FAILURE: 'FETCH_NOWPLAYING_FAILURE',
};

export default NowPlayingActionTypes;
