const UserSessionTypes = {
  FETCH_SESSION_START: 'FETCH_SESSION_START',
  FETCH_SESSION_SUCCESS: 'FETCH_SESSION_SUCCESS',
  FETCH_SESSION_FAILURE: 'FETCH_SESSION_FAILURE',
};

export default UserSessionTypes;
