const UserSessionTypes = {
  FETCH_SESSION_START: 'FETCH_SESSION_START',
  FETCH_SESSION_SUCCESS: 'FETCH_SESSION_SUCCESS',
  FETCH_SESSION_FAILURE: 'FETCH_SESSION_FAILURE',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
};

export default UserSessionTypes;
