const UpcomingActionTypes = {
  FETCH_UPCOMING_START: 'FETCH_UPCOMING_START',
  FETCH_UPCOMING_SUCCESS: 'FETCH_UPCOMING_SUCCESS',
  FETCH_UPCOMING_FAILURE: 'FETCH_UPCOMING_FAILURE',
};

export default UpcomingActionTypes;
