const PopularActionTypes = {
  FETCH_POPULAR_START: 'FETCH_POPULAR_START',
  FETCH_POPULAR_SUCCESS: 'FETCH_POPULAR_SUCCESS',
  FETCH_POPULAR_FAILURE: 'FETCH_POPULAR_FAILURE',
};

export default PopularActionTypes;
